version: '3.8'

services:
  cmp-backend:
    container_name: cmp-backend-dev
    image: adalmia/rb-cmp-backend:dev
    ports:
      - "8002:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PHOENIX_API_KEY=${PHOENIX_API_KEY}
      - PHOENIX_ENDPOINT=${PHOENIX_ENDPOINT}
      - ENV=${ENV}
      - FRAPPE_BACKEND_BASE_URL=${FRAPPE_BACKEND_BASE_URL}
      - FRAPPE_BACKEND_CLIENT_ID=${FRAPPE_BACKEND_CLIENT_ID}
      - FRAPPE_BACKEND_CLIENT_SECRET=${FRAPPE_BACKEND_CLIENT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - /appdata_dev:/appdata
